USE [SIIR-ProdV1];
GO

-- Verificar la estructura de la tabla TM02_ENTIDADFINANCIERA
SELECT 
    COLUMN_NAME,
    DATA_TYPE,
    IS_NULLABLE,
    CHARACTER_MAXIMUM_LENGTH
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'TM02_ENTIDADFINANCIERA'
ORDER BY ORDINAL_POSITION;

-- También ver algunos datos de ejemplo
SELECT TOP 5 * FROM [SIIR-ProdV1].[dbo].[TM02_ENTIDADFINANCIERA];