-- Verificar los tipos de datos de los campos monetarios
SELECT 
    COLUMN_NAME,
    DATA_TYPE,
    NUMERIC_PRECISION,
    NUMERIC_SCALE,
    IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'TM02_ENTIDADFINANCIERA' 
AND COLUMN_NAME IN ('TM02_CapitalSuscrito', 'TM02_ValorPagado')
ORDER BY COLUMN_NAME;