-- Verificar las columnas de la tabla TM02_ENTIDADFINANCIERA relacionadas con representante
USE [SIIR-ProdV1]
GO

SELECT COLUMN_NAME, DATA_TYPE, IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'TM02_ENTIDADFINANCIERA' 
  AND COLUMN_NAME LIKE '%Rep%'
ORDER BY COLUMN_NAME

-- También verificar todas las columnas que contienen 'Apellido'
SELECT COLUMN_NAME, DATA_TYPE, IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'TM02_ENTIDADFINANCIERA' 
  AND COLUMN_NAME LIKE '%Apellido%'
ORDER BY COLUMN_NAME